<?xml version="1.0" encoding="utf-8"?><Database Name="ServiceOrderManager" Class="ServiceOrdersDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=.\sql2005;Initial Catalog=ServiceOrderManager;Integrated Security=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="ServiceOrderManagerConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Settings" Member="Settings">
    <Type Name="Setting">
      <Column Name="SettingID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="ServiceOrderNumberPrefix" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.ServiceOrderDetails" Member="ServiceOrderDetails">
    <Type Name="ServiceOrderDetail">
      <Column Name="ServiceOrderDetailID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ServiceOrderID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Qty" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Description" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="UnitPrice" Type="System.Decimal" DbType="Decimal(18,4)" CanBeNull="true" />
      <Association Name="ServiceOrder_ServiceOrderDetail" Member="ServiceOrder" ThisKey="ServiceOrderID" OtherKey="ServiceOrderID" Type="ServiceOrder" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.ServiceOrderStatus" Member="ServiceOrderStatus">
    <Type Name="ServiceOrderStatus">
      <Column Name="ServiceOrderStatusID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Description" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="OrderNumber" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CreatedBy" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="CreatedDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Association Name="ServiceOrderStatus_ServiceOrder" Member="ServiceOrders" ThisKey="ServiceOrderStatusID" OtherKey="StatusID" Type="ServiceOrder" />
    </Type>
  </Table>
  <Table Name="dbo.ServiceOrders" Member="ServiceOrders">
    <Type Name="ServiceOrder">
      <Column Name="ServiceOrderID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="SupplierID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ServiceOrderNumber" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="TermsAndConditions" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="AcceptanceName" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="ApprovedBy" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="PaymentTerms" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="PercentageOfCompletion" Type="System.Decimal" DbType="Decimal(18,1)" CanBeNull="true" />
      <Column Name="StatusID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="IsPaid" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="IsApproved" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Association Name="ServiceOrder_ServiceOrderDetail" Member="ServiceOrderDetails" ThisKey="ServiceOrderID" OtherKey="ServiceOrderID" Type="ServiceOrderDetail" />
      <Association Name="ServiceOrderStatus_ServiceOrder" Member="ServiceOrderStatus" ThisKey="StatusID" OtherKey="ServiceOrderStatusID" Type="ServiceOrderStatus" IsForeignKey="true" />
    </Type>
  </Table>
</Database>